### ISSUE TITLE
Better understanding of the encryption in Matrix

### ISSUE THREAD

**Issue by heroinedor** [tchapgouv/synapse-on-k8s#180]
Read the Matrix documentation about this subject.
Maybe contact the healthcare IM editors and see how they do it.

Definition of done : 
small report to the team about : 
- how it works on Matrix
- impact on our federation
- how it works on other healthcare IM

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/180?planning-poker) with Zenhub @JDixmier @ad2ien

**Comment by ad2ien** [comment]
Because we had trouble using encrypted rooms with https://github.com/matrix-org/matrix-appservice-slack we wanted to confirm that it was possible to use encrypted rooms with a bridge. To confirm this, https://github.com/mautrix/slack was deployed. An encrypted room was created and the slack bot was invited.
When issuing a command, the message is decrypted and the command is answered.
This is actually done in the mautrix sdk : https://github.com/mautrix/go

Actually all stable sdk should be able to decrypt messages https://matrix.org/ecosystem/sdks/ and there's in python, kotlin, typescript, Rust and Go

 Impact on the federation : in a data protection prospective, the bridge could be a vulnerability and should be properly audited.
